const demoProjects = [
  {
    user_id: 2,
    name: "Portfolio Website",
    category: "Web Development",
    github_url: "https://github.com/example/portfolio",
    description: "A modern, responsive portfolio website built with HTML, CSS, and JavaScript. Features smooth scrolling, dark mode toggle, and contact form.",
    author: "Sarah Johnson",
    stars: 45,
    forks: 12,
    language: "JavaScript",
    topics: "portfolio, responsive, dark-mode",
    tags: "html, css, javascript, responsive, portfolio",
    created_at: "2024-01-15T10:30:00Z",
    status: "approved",
    upvotes: 23,
    views: 450,
    demo_url: "https://demo-portfolio.netlify.app"
  },
  {
    user_id: 2,
    name: "Task Manager App",
    category: "Web Development",
    github_url: "https://github.com/example/task-manager",
    description: "Full-stack task management application with user authentication, real-time updates, and priority sorting. Built with Node.js and MongoDB.",
    author: "Michael Chen",
    stars: 78,
    forks: 34,
    language: "JavaScript",
    topics: "nodejs, mongodb, crud, authentication",
    tags: "nodejs, mongodb, express, react, fullstack",
    created_at: "2024-02-10T14:20:00Z",
    status: "approved",
    upvotes: 56,
    views: 820,
    demo_url: "https://task-manager-demo.herokuapp.com"
  },
  {
    user_id: 2,
    name: "Weather Forecast App",
    category: "Web Development",
    github_url: "https://github.com/example/weather-app",
    description: "Real-time weather application using OpenWeather API. Shows 7-day forecast, hourly updates, and location-based weather. Clean UI with weather animations.",
    author: "Emily Rodriguez",
    stars: 92,
    forks: 28,
    language: "JavaScript",
    topics: "api, weather, geolocation",
    tags: "api, weather, javascript, react, openweather",
    created_at: "2024-01-28T09:15:00Z",
    status: "approved",
    upvotes: 67,
    views: 1100,
    demo_url: "https://weather-app-demo.vercel.app"
  },
  {
    user_id: 2,
    name: "Image Classifier AI",
    category: "AI/ML",
    github_url: "https://github.com/example/image-classifier",
    description: "Deep learning model for image classification using TensorFlow. Trained on 10,000+ images with 95% accuracy. Includes web interface for real-time predictions.",
    author: "David Kim",
    stars: 156,
    forks: 45,
    language: "Python",
    topics: "machine-learning, tensorflow, computer-vision",
    tags: "python, tensorflow, ai, machine-learning, deep-learning",
    created_at: "2024-02-20T16:45:00Z",
    status: "approved",
    upvotes: 89,
    views: 1450,
    demo_url: null
  },
  {
    user_id: 2,
    name: "Sentiment Analysis Bot",
    category: "AI/ML",
    github_url: "https://github.com/example/sentiment-bot",
    description: "NLP-based sentiment analysis tool for social media posts. Uses BERT model to classify emotions with 92% accuracy. Includes Twitter API integration.",
    author: "Priya Patel",
    stars: 134,
    forks: 52,
    language: "Python",
    topics: "nlp, sentiment-analysis, bert, twitter",
    tags: "python, nlp, bert, ai, twitter, sentiment-analysis",
    created_at: "2024-03-05T11:30:00Z",
    status: "approved",
    upvotes: 71,
    views: 980,
    demo_url: null
  },
  {
    user_id: 2,
    name: "2D Platformer Game",
    category: "Game Development",
    github_url: "https://github.com/example/platformer-game",
    description: "Retro-style platformer game with 15 levels, power-ups, and boss battles. Built with Unity and C#. Features custom pixel art and chiptune music.",
    author: "Alex Thompson",
    stars: 203,
    forks: 67,
    language: "C#",
    topics: "unity, game-dev, platformer, 2d",
    tags: "unity, csharp, game-dev, 2d, platformer",
    created_at: "2024-01-10T13:00:00Z",
    status: "approved",
    upvotes: 124,
    views: 1750,
    demo_url: "https://platformer-game.itch.io"
  },
  {
    user_id: 2,
    name: "Puzzle Quest",
    category: "Game Development",
    github_url: "https://github.com/example/puzzle-quest",
    description: "Match-3 puzzle game with RPG elements. Features character progression, daily challenges, and multiplayer mode. Built with Godot Engine.",
    author: "Jessica Lee",
    stars: 167,
    forks: 43,
    language: "GDScript",
    topics: "godot, puzzle, rpg, multiplayer",
    tags: "godot, game-dev, puzzle, rpg, multiplayer",
    created_at: "2024-02-14T15:20:00Z",
    status: "approved",
    upvotes: 98,
    views: 1320,
    demo_url: null
  },
  {
    user_id: 2,
    name: "Fitness Tracker Mobile",
    category: "Mobile App",
    github_url: "https://github.com/example/fitness-tracker",
    description: "Cross-platform fitness tracking app with workout plans, calorie counter, and progress charts. Built with React Native and Firebase.",
    author: "Marcus Williams",
    stars: 189,
    forks: 56,
    language: "JavaScript",
    topics: "react-native, firebase, fitness, mobile",
    tags: "react-native, firebase, mobile, fitness, health",
    created_at: "2024-03-01T10:00:00Z",
    status: "approved",
    upvotes: 112,
    views: 1580,
    demo_url: null
  },
  {
    user_id: 2,
    name: "Recipe Sharing App",
    category: "Mobile App",
    github_url: "https://github.com/example/recipe-app",
    description: "Social recipe sharing platform with photo uploads, ingredient lists, and cooking timers. Features user ratings and favorites. Built with Flutter.",
    author: "Olivia Martinez",
    stars: 145,
    forks: 38,
    language: "Dart",
    topics: "flutter, firebase, recipes, social",
    tags: "flutter, dart, mobile, firebase, social",
    created_at: "2024-01-25T14:30:00Z",
    status: "approved",
    upvotes: 87,
    views: 1240,
    demo_url: null
  },
  {
    user_id: 2,
    name: "Markdown Editor",
    category: "Other",
    github_url: "https://github.com/example/markdown-editor",
    description: "Lightweight markdown editor with live preview, syntax highlighting, and export to PDF. Supports GitHub Flavored Markdown and custom themes.",
    author: "Ryan Anderson",
    stars: 98,
    forks: 29,
    language: "JavaScript",
    topics: "markdown, editor, preview, pdf",
    tags: "javascript, markdown, editor, pdf, electron",
    created_at: "2024-02-08T12:45:00Z",
    status: "approved",
    upvotes: 54,
    views: 780,
    demo_url: "https://markdown-editor-demo.netlify.app"
  },
  {
    user_id: 2,
    name: "Code Snippet Manager",
    category: "Other",
    github_url: "https://github.com/example/snippet-manager",
    description: "Desktop app for organizing and searching code snippets. Features syntax highlighting for 50+ languages, tags, and cloud sync. Built with Electron.",
    author: "Sophie Taylor",
    stars: 176,
    forks: 48,
    language: "JavaScript",
    topics: "electron, snippets, productivity",
    tags: "electron, javascript, productivity, snippets, desktop",
    created_at: "2024-03-10T09:20:00Z",
    status: "approved",
    upvotes: 93,
    views: 1150,
    demo_url: null
  },
  {
    user_id: 2,
    name: "Blockchain Voting System",
    category: "Other",
    github_url: "https://github.com/example/blockchain-voting",
    description: "Decentralized voting system using Ethereum smart contracts. Ensures transparency and prevents fraud. Includes web interface for casting votes.",
    author: "Aiden Brown",
    stars: 234,
    forks: 78,
    language: "Solidity",
    topics: "blockchain, ethereum, smart-contracts, voting",
    tags: "blockchain, ethereum, solidity, smart-contracts, web3",
    created_at: "2024-01-20T16:00:00Z",
    status: "approved",
    upvotes: 145,
    views: 2100,
    demo_url: null
  },
  // Pending projects for testing
  {
    user_id: 2,
    name: "Chat Application",
    category: "Web Development",
    github_url: "https://github.com/example/chat-app",
    description: "Real-time chat application with Socket.io, user authentication, and private messaging.",
    author: "Demo Student",
    stars: 15,
    forks: 5,
    language: "JavaScript",
    topics: "chat, socketio, realtime",
    tags: "nodejs, socketio, chat, realtime, websockets",
    created_at: "2024-03-15T10:00:00Z",
    status: "pending",
    upvotes: 0,
    views: 25,
    demo_url: null
  },
  {
    user_id: 2,
    name: "E-commerce Platform",
    category: "Web Development",
    github_url: "https://github.com/example/ecommerce",
    description: "Full-featured e-commerce platform with shopping cart, payment integration, and order management.",
    author: "Demo Student",
    stars: 8,
    forks: 2,
    language: "JavaScript",
    topics: "ecommerce, shopping, payment",
    tags: "react, nodejs, ecommerce, stripe, mongodb",
    created_at: "2024-03-16T14:00:00Z",
    status: "pending",
    upvotes: 0,
    views: 18,
    demo_url: null
  }
];

module.exports = demoProjects;